#DEPENDENTES
INSERT INTO `dependentes`(`DEP_NV_PARENTESCO`, `DEP_NOME`, `DEP_DATA_NASCIMENTO`, `FK_PACIENTES_PAC_ID`, `FK_PACIENTES_FK_USUARIO_COMUM_USC_ID`, `FK_RESPONSAVEIS_RES_ID`, `FK_RESPONSAVEIS_FK_PACIENTES_PAC_ID`, `FK_RESPONSAVEIS_FK_PACIENTES_FK_USUARIO_COMUM_USC_ID`) VALUES ('1','José','2000-10-20','1','1','1','1','1');

INSERT INTO `dependentes`(`DEP_NV_PARENTESCO`, `DEP_NOME`, `DEP_DATA_NASCIMENTO`, `FK_PACIENTES_PAC_ID`, `FK_PACIENTES_FK_USUARIO_COMUM_USC_ID`, `FK_RESPONSAVEIS_RES_ID`, `FK_RESPONSAVEIS_FK_PACIENTES_PAC_ID`, `FK_RESPONSAVEIS_FK_PACIENTES_FK_USUARIO_COMUM_USC_ID`) VALUES ('2','Maria','2000-11-21','2','2','2','2','2');

INSERT INTO `dependentes`(`DEP_NV_PARENTESCO`, `DEP_NOME`, `DEP_DATA_NASCIMENTO`, `FK_PACIENTES_PAC_ID`, `FK_PACIENTES_FK_USUARIO_COMUM_USC_ID`, `FK_RESPONSAVEIS_RES_ID`, `FK_RESPONSAVEIS_FK_PACIENTES_PAC_ID`, `FK_RESPONSAVEIS_FK_PACIENTES_FK_USUARIO_COMUM_USC_ID`) VALUES ('3','Victor','2010-12-22','3','3','3','3','3');

INSERT INTO `dependentes`(`DEP_NV_PARENTESCO`, `DEP_NOME`, `DEP_DATA_NASCIMENTO`, `FK_PACIENTES_PAC_ID`, `FK_PACIENTES_FK_USUARIO_COMUM_USC_ID`, `FK_RESPONSAVEIS_RES_ID`, `FK_RESPONSAVEIS_FK_PACIENTES_PAC_ID`, `FK_RESPONSAVEIS_FK_PACIENTES_FK_USUARIO_COMUM_USC_ID`) VALUES ('4','Letícia','2004-01-01','4','4','4','4','4');

INSERT INTO `dependentes`(`DEP_NV_PARENTESCO`, `DEP_NOME`, `DEP_DATA_NASCIMENTO`, `FK_PACIENTES_PAC_ID`, `FK_PACIENTES_FK_USUARIO_COMUM_USC_ID`, `FK_RESPONSAVEIS_RES_ID`, `FK_RESPONSAVEIS_FK_PACIENTES_PAC_ID`, `FK_RESPONSAVEIS_FK_PACIENTES_FK_USUARIO_COMUM_USC_ID`) VALUES ('5','Rafael','1998-02-10','5','5','5','5','5');