/* Modelo_relacional_integrado: */

CREATE DATABASE omnimed CHARACTER SET utf8 COLLATE utf8_bin;

USE omnimed;

CREATE TABLE CONTATOS_SETORIAIS (
    CSE_TELEFONE_CELULAR VARCHAR(20),
    CSE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CSE_TELEFONE_FIXO VARCHAR(20) NOT NULL,
    CSE_SETOR VARCHAR(200) NOT NULL UNIQUE,
    CSE_EMAIL VARCHAR(200) NOT NULL
);

CREATE TABLE PACIENTES (
    PAC_ID INTEGER AUTO_INCREMENT,
    PAC_EMAIL VARCHAR(200) NOT NULL,
    PAC_STATUS BOOLEAN NOT NULL,
    FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL,
    FK_PLANOS_PLN_ID INTEGER NOT NULL,
    PRIMARY KEY (PAC_ID, FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE RESPONSAVEIS (
    RES_QTD_FILHOS INTEGER NOT NULL,
    RES_QUAIS_TRAT_MED VARCHAR(200),
    RES_TEM_ALERGIA_MEDICA BOOLEAN NOT NULL,
    RES_QUAL_MEDICACAO VARCHAR(200),
    RES_QUAIS_ALERGIAS VARCHAR(200),
    RES_TEL_CELULAR1 VARCHAR(20),
    RES_UTILIZA_MEDICACAO BOOLEAN NOT NULL,
    RES_TEL_CELULAR2 VARCHAR(20),
    RES_ID INTEGER AUTO_INCREMENT,
    RES_TEM_FILHOS BOOLEAN NOT NULL,
    RES_QUAIS_DOENCAS_CRONICAS VARCHAR(200),
    RES_DOENCAS_CRONICAS BOOLEAN,
    RES_TRATAMENTO_MEDICO BOOLEAN,
    FK_PACIENTES_PAC_ID INTEGER NOT NULL,
    FK_PACIENTES_FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL,
    PRIMARY KEY (RES_ID, FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE USUARIO_COMUM (
    USC_SEXO INTEGER NOT NULL,
    USC_CIDADE VARCHAR(100) NOT NULL,
    USC_BAIRRO VARCHAR(100) NOT NULL,
    USC_DATA_NASCIMENTO DATE NOT NULL,
    USC_ESTADO INTEGER NOT NULL,
    USC_SENHA VARCHAR(200) NOT NULL,
    USC_ORGAO_EMISSOR VARCHAR(10),
    USC_CPF VARCHAR(20) NOT NULL,
    USC_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USC_NOME VARCHAR(180) NOT NULL,
    USC_RG VARCHAR(15) NOT NULL,
    USC_LOGRADOURO VARCHAR(200) NOT NULL,
    USC_NUMERO VARCHAR(10) NOT NULL,
    UNIQUE (USC_CPF, USC_RG)
);

CREATE TABLE DEPENDENTES (
    DEP_NV_PARENTESCO INTEGER NOT NULL,
    DEP_ID INTEGER AUTO_INCREMENT,
    DEP_NOME VARCHAR(100) NOT NULL,
    DEP_DATA_NASCIMENTO DATE NOT NULL,
    FK_PACIENTES_PAC_ID INTEGER NOT NULL,
    FK_PACIENTES_FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL,
    FK_RESPONSAVEIS_RES_ID INTEGER NOT NULL,
    FK_RESPONSAVEIS_FK_PACIENTES_PAC_ID INTEGER NOT NULL,
    FK_RESPONSAVEIS_FK_PACIENTES_FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL,
    PRIMARY KEY (DEP_ID, FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE FUNCIONARIOS (
    FUN_ID INTEGER AUTO_INCREMENT,
    FUN_PRONTUARIO VARCHAR(8) NOT NULL,
    FUN_CATEGORIA INTEGER NOT NULL,
    FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL,
    PRIMARY KEY (FUN_ID, FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE MEDICOS (
    MED_ID INTEGER AUTO_INCREMENT,
    FK_FUNCIONARIOS_FUN_ID INTEGER NOT NULL,
    FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL,
    PRIMARY KEY (MED_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE CONTABILIDADE (
    CON_ID INTEGER AUTO_INCREMENT,
    FK_FUNCIONARIOS_FUN_ID INTEGER NOT NULL,
    FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL,
    PRIMARY KEY (CON_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE ENFERMEIROS (
    ENF_ID INTEGER AUTO_INCREMENT,
    FK_FUNCIONARIOS_FUN_ID INTEGER NOT NULL,
    FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL,
    PRIMARY KEY (ENF_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE ADMINISTRATIVO (
    ADM_FUNCAO INTEGER NOT NULL,
    ADM_ID INTEGER AUTO_INCREMENT,
    ADM_DATA_DEMISSAO DATE,
    ADM_DATA_ADMISSAO DATE NOT NULL,
    ADM_CLINICA INTEGER NOT NULL,
    ADM_SALARIO FLOAT NOT NULL,
    ADM_CRM VARCHAR(20) NOT NULL,
    ADM_TELEFONE_CELULAR VARCHAR(20) NOT NULL,
    FK_FUNCIONARIOS_FUN_ID INTEGER NOT NULL,
    FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL,
    PRIMARY KEY (ADM_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
);
/*
CREATE TABLE CLINICAS_MEDICAS (
    CLI_CONTATO2 VARCHAR(20),
    CLI_CONTATO1 VARCHAR(20),
    CLI_RAZAO_SOCIAL VARCHAR(200) NOT NULL,
    CLI_ID INTEGER AUTO_INCREMENT,
    CLI_DATA_FUNDACAO DATE NOT NULL,
    CLI_CNPJ VARCHAR(30) NOT NULL,
    FK_ADMINISTRATIVO_ADM_ID INTEGER NOT NULL,
    FK_ADMINISTRATIVO_FK_FUNCIONARIOS_FUN_ID INTEGER NOT NULL,
    FK_ADMINISTRATIVO_FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL,
    PRIMARY KEY (CLI_ID, FK_ADMINISTRATIVO_ADM_ID, FK_ADMINISTRATIVO_FK_FUNCIONARIOS_FUN_ID, FK_ADMINISTRATIVO_FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
);*/

CREATE TABLE AGENDAMENTOS (
    AGD_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    AGD_STATUS INTEGER NOT NULL,
    AGD_ENCAMINHAMENTOS BOOLEAN NOT NULL,
    AGD_DATA DATE NOT NULL,
    AGD_HORARIO TIME NOT NULL,
    AGD_MEET_LINK VARCHAR(255),
    FK_PACIENTES_PAC_ID INTEGER NOT NULL,
    FK_PACIENTES_FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL,
    FK_MEDICOS_MED_ID INTEGER NOT NULL,
    FK_MEDICOS_FK_FUNCIONARIOS_FUN_ID INTEGER NOT NULL,
    FK_MEDICOS_FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL,
    FK_ESPECIALIDADES_MEDICAS_ESM_ID INTEGER NOT NULL,
    AGD_TRIAGEM_REALIZADA BOOLEAN NOT NULL,
    AGD_RETORNO BOOLEAN NOT NULL
);

CREATE TABLE TRIAGENS (
    TRG_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TRG_SINTOMAS VARCHAR(255) NOT NULL,
    TRG_TABELA_DOR INTEGER NOT NULL,
    TRG_PRESSAO_SISTOLICA INTEGER,
    TRG_TEMPERATURA DOUBLE,
    TRG_PRESSAO_DIASTOLICA INTEGER,
    FK_AGENDAMENTOS_AGD_ID INTEGER NOT NULL
);

CREATE TABLE CONSULTAS_ONLINE (
    CNS_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CNS_DATA DATE,
    CNS_ANOTACOES VARCHAR(255),
    CNS_SINTOMAS_IDENTIFICADOS VARCHAR(255),
    CNS_DIAGNOSTICO VARCHAR(250),
    FK_AGENDAMENTOS_AGD_ID INTEGER NOT NULL
);

CREATE TABLE PRESCRICOES (
    PRC_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRC_DURACAO_TRATAMENTO VARCHAR(60) NOT NULL,
    PRC_OBSERVACOES VARCHAR(500) NOT NULL,
    PRC_ASSINATURA_MEDICO VARCHAR(255) NOT NULL,
    PRC_DATA_EMISSAO DATE NOT NULL,
    FK_CONSULTAS_ONLINE_CNS_ID INTEGER NOT NULL,
    FK_MEDICOS_MED_ID INTEGER NOT NULL,
    FK_MEDICOS_FK_FUNCIONARIOS_FUN_ID INTEGER NOT NULL,
    FK_MEDICOS_FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL
);

CREATE TABLE REMEDIOS (
    RMD_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    RMD_NOME VARCHAR(100) NOT NULL UNIQUE,
    RMD_VIA_DOSAGEM INTEGER,
    RMD_INDICACAO TEXT,
    RMD_CONTRAINDICACAO TEXT,
    RMD_DOSAGEM INTEGER(4) NOT NULL,
    FK_FORMAS_FARMACEUTICAS_FRM_ID INTEGER NOT NULL
);

CREATE TABLE FORMAS_FARMACEUTICAS (
    FRM_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FRM_DESCRICAO VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE FINALIDADE_REMEDIOS (
    FIN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FIN_DESCRICAO VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE ESPECIALIDADES_MEDICAS (
    ESM_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ESM_DESCRICAO VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE EXAMES (
    EXM_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EXM_NOME VARCHAR(100),
    EXM_ANEXO_GUIA BLOB NOT NULL,
    EXM_OBS_SECRETARIO VARCHAR(200),
    EXM_AGENDAMENTO DATETIME,
    EXM_AUTORIZADO BOOLEAN,
    EXM_ANEXO_RESULTADO BLOB NOT NULL,
    EXM_OBS_PACIENTE VARCHAR(200),
    FK_MEDICOS_MED_ID INTEGER NOT NULL,
    FK_MEDICOS_FK_FUNCIONARIOS_FUN_ID INTEGER NOT NULL,
    FK_MEDICOS_FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL,
    FK_PACIENTES_PAC_ID INTEGER NOT NULL,
    FK_PACIENTES_FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL,
    UNIQUE (EXM_ANEXO_GUIA, EXM_ANEXO_RESULTADO)
);

CREATE TABLE PLANOS (
    PLN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PLN_INSTITUICAO VARCHAR(100) NOT NULL,
    PLN_NOME VARCHAR(100) NOT NULL UNIQUE,
    PLN_PRECO DOUBLE(8,2) NOT NULL
);

CREATE TABLE BENEFICIOS (
    BNF_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    BNF_DESCRICAO VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE VALORES_DEPENDENTES (
    VPD_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VPD_IDADE_MAXIMA INTEGER(3) NOT NULL,
    VPD_IDADE_MINIMA INTEGER(3) NOT NULL,
    VPD_VALOR DOUBLE(6,2) NOT NULL,
    FK_PLANOS_PLN_ID INTEGER NOT NULL
);

CREATE TABLE PAGAMENTOS (
    PGD_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PGD_VENCIMENTO DATE NOT NULL,
    PGD_DATA_PAGAMENTO DATE,
    PGD_VALOR_TOTAL DOUBLE(8,2) NOT NULL,
    FK_PACIENTES_PAC_ID INTEGER NOT NULL,
    FK_PACIENTES_FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL
);

CREATE TABLE PAGAMENTOS_MEDICOS (
    PGM_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PGM_DATA_PAGAMENTO_REALIZADO DATE,
    PGM_DATA_DE_PAGAMENTO DATE NOT NULL,
    PGM_SALARIO DOUBLE(8,2) NOT NULL,
    PGM_VALOR_COMISSAO DOUBLE(8,2) NOT NULL,
    PGM_VALOR_TOTAL DOUBLE(8,2) NOT NULL,
    FK_MEDICOS_MED_ID INTEGER NOT NULL,
    FK_MEDICOS_FK_FUNCIONARIOS_FUN_ID INTEGER NOT NULL,
    FK_MEDICOS_FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL
);

CREATE TABLE USO_REMEDIO (
	URM_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_FINALIDADE_REMEDIOS_FIN_ID INTEGER NOT NULL,
    FK_REMEDIOS_RMD_ID INTEGER NOT NULL
);

CREATE TABLE REMEDIOS_PRESCRICOES (
    FK_PRESCRICOES_PRC_ID INTEGER NOT NULL,
    FK_REMEDIOS_RMD_ID INTEGER NOT NULL,
    RMP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    RMP_ESQUEMA_POSOLOGICO VARCHAR(200) NOT NULL
);

CREATE TABLE ESPECIALISTAS (
    FK_MEDICOS_MED_ID INTEGER NOT NULL,
    FK_MEDICOS_FK_FUNCIONARIOS_FUN_ID INTEGER NOT NULL,
    FK_MEDICOS_FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INTEGER NOT NULL,
    FK_ESPECIALIDADES_MEDICAS_ESM_ID INTEGER NOT NULL,
    ESP_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE PLANOS_BENEFICIOS (
    FK_BENEFICIOS_BNF_ID INTEGER NOT NULL,
    FK_PLANOS_PLN_ID INTEGER NOT NULL,
    PBN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PBN_VALOR_BENEFICIO INTEGER(4) NOT NULL
);
 
ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTES_2
    FOREIGN KEY (FK_USUARIO_COMUM_USC_ID)
    REFERENCES USUARIO_COMUM (USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTES_3
    FOREIGN KEY (FK_PLANOS_PLN_ID)
    REFERENCES PLANOS (PLN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RESPONSAVEIS ADD CONSTRAINT FK_RESPONSAVEIS_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
    REFERENCES PACIENTES (PAC_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DEPENDENTES ADD CONSTRAINT FK_DEPENDENTES_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
    REFERENCES PACIENTES (PAC_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DEPENDENTES ADD CONSTRAINT FK_DEPENDENTES_3
    FOREIGN KEY (FK_RESPONSAVEIS_RES_ID, FK_RESPONSAVEIS_FK_PACIENTES_PAC_ID, FK_RESPONSAVEIS_FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
    REFERENCES RESPONSAVEIS (RES_ID, FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE FUNCIONARIOS ADD CONSTRAINT FK_FUNCIONARIOS_2
    FOREIGN KEY (FK_USUARIO_COMUM_USC_ID)
    REFERENCES USUARIO_COMUM (USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE MEDICOS ADD CONSTRAINT FK_MEDICOS_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES FUNCIONARIOS (FUN_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CONTABILIDADE ADD CONSTRAINT FK_CONTABILIDADE_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES FUNCIONARIOS (FUN_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ENFERMEIROS ADD CONSTRAINT FK_ENFERMEIROS_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES FUNCIONARIOS (FUN_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ADMINISTRATIVO ADD CONSTRAINT FK_ADMINISTRATIVO_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES FUNCIONARIOS (FUN_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 /*
ALTER TABLE CLINICAS_MEDICAS ADD CONSTRAINT FK_CLINICAS_MEDICAS_2
    FOREIGN KEY (FK_ADMINISTRATIVO_ADM_ID, FK_ADMINISTRATIVO_FK_FUNCIONARIOS_FUN_ID, FK_ADMINISTRATIVO_FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES ADMINISTRATIVO (ADM_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 */
ALTER TABLE AGENDAMENTOS ADD CONSTRAINT FK_AGENDAMENTOS_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
    REFERENCES PACIENTES (PAC_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE AGENDAMENTOS ADD CONSTRAINT FK_AGENDAMENTOS_3
    FOREIGN KEY (FK_MEDICOS_MED_ID, FK_MEDICOS_FK_FUNCIONARIOS_FUN_ID, FK_MEDICOS_FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES MEDICOS (MED_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE AGENDAMENTOS ADD CONSTRAINT FK_AGENDAMENTOS_4
    FOREIGN KEY (FK_ESPECIALIDADES_MEDICAS_ESM_ID)
    REFERENCES ESPECIALIDADES_MEDICAS (ESM_ID)
    ON DELETE CASCADE;
 
ALTER TABLE TRIAGENS ADD CONSTRAINT FK_TRIAGENS_2
    FOREIGN KEY (FK_AGENDAMENTOS_AGD_ID)
    REFERENCES AGENDAMENTOS (AGD_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CONSULTAS_ONLINE ADD CONSTRAINT FK_CONSULTAS_ONLINE_2
    FOREIGN KEY (FK_AGENDAMENTOS_AGD_ID)
    REFERENCES AGENDAMENTOS (AGD_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PRESCRICOES ADD CONSTRAINT FK_PRESCRICOES_2
    FOREIGN KEY (FK_CONSULTAS_ONLINE_CNS_ID)
    REFERENCES CONSULTAS_ONLINE (CNS_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PRESCRICOES ADD CONSTRAINT FK_PRESCRICOES_3
    FOREIGN KEY (FK_MEDICOS_MED_ID, FK_MEDICOS_FK_FUNCIONARIOS_FUN_ID, FK_MEDICOS_FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES MEDICOS (MED_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE REMEDIOS ADD CONSTRAINT FK_REMEDIOS_2
    FOREIGN KEY (FK_FORMAS_FARMACEUTICAS_FRM_ID)
    REFERENCES FORMAS_FARMACEUTICAS (FRM_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EXAMES ADD CONSTRAINT FK_EXAMES_2
    FOREIGN KEY (FK_MEDICOS_MED_ID, FK_MEDICOS_FK_FUNCIONARIOS_FUN_ID, FK_MEDICOS_FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES MEDICOS (MED_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EXAMES ADD CONSTRAINT FK_EXAMES_3
    FOREIGN KEY (FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
    REFERENCES PACIENTES (PAC_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE VALORES_DEPENDENTES ADD CONSTRAINT FK_VALORES_DEPENDENTES_2
    FOREIGN KEY (FK_PLANOS_PLN_ID)
    REFERENCES PLANOS (PLN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PAGAMENTOS ADD CONSTRAINT FK_PAGAMENTOS_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
    REFERENCES PACIENTES (PAC_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PAGAMENTOS_MEDICOS ADD CONSTRAINT FK_PAGAMENTOS_MEDICOS_2
    FOREIGN KEY (FK_MEDICOS_MED_ID, FK_MEDICOS_FK_FUNCIONARIOS_FUN_ID, FK_MEDICOS_FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES MEDICOS (MED_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE USO_REMEDIO ADD CONSTRAINT FK_USO_REMEDIO_1
    FOREIGN KEY (FK_FINALIDADE_REMEDIOS_FIN_ID)
    REFERENCES FINALIDADE_REMEDIOS (FIN_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE USO_REMEDIO ADD CONSTRAINT FK_USO_REMEDIO_2
    FOREIGN KEY (FK_REMEDIOS_RMD_ID)
    REFERENCES REMEDIOS (RMD_ID)
    ON DELETE CASCADE;
 
ALTER TABLE REMEDIOS_PRESCRICOES ADD CONSTRAINT FK_REMEDIOS_PRESCRICOES_2
    FOREIGN KEY (FK_PRESCRICOES_PRC_ID)
    REFERENCES PRESCRICOES (PRC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE REMEDIOS_PRESCRICOES ADD CONSTRAINT FK_REMEDIOS_PRESCRICOES_3
    FOREIGN KEY (FK_REMEDIOS_RMD_ID)
    REFERENCES REMEDIOS (RMD_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ESPECIALISTAS ADD CONSTRAINT FK_ESPECIALISTAS_2
    FOREIGN KEY (FK_MEDICOS_MED_ID, FK_MEDICOS_FK_FUNCIONARIOS_FUN_ID, FK_MEDICOS_FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES MEDICOS (MED_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ESPECIALISTAS ADD CONSTRAINT FK_ESPECIALISTAS_3
    FOREIGN KEY (FK_ESPECIALIDADES_MEDICAS_ESM_ID)
    REFERENCES ESPECIALIDADES_MEDICAS (ESM_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PLANOS_BENEFICIOS ADD CONSTRAINT FK_PLANOS_BENEFICIOS_2
    FOREIGN KEY (FK_BENEFICIOS_BNF_ID)
    REFERENCES BENEFICIOS (BNF_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE PLANOS_BENEFICIOS ADD CONSTRAINT FK_PLANOS_BENEFICIOS_3
    FOREIGN KEY (FK_PLANOS_PLN_ID)
    REFERENCES PLANOS (PLN_ID)
    ON DELETE CASCADE;